### ISSUE TITLE
make jsxgraph available for all ILIAS page editor pages

### ISSUE THREAD

**Issue by mglaubitz** [pascalgrube/jsxgraphpc#3]
make jsxgraph available for all ILIAS page editor pages. learning modules are great, but there are so many other great habitats for the jsxgraphs... :)

**Comment by pascalseeland** [comment]
Enabling all places where you could enable a PageObject probably don't make sense.
Could you please execute the following sql-query on your ilias db:
`SELECT *  FROM``copg_pobj_def``LIMIT 0 , 30;`
It gives you a list of all possible places. Just tell me which ones you think make sense.
